[2023-04-25T20:25:22.088+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/snow_air.py
[2023-04-25T20:25:22.090+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-25T20:25:22.093+0000] {logging_mixin.py:120} INFO - [2023-04-25T20:25:22.093+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-25T20:25:22.114+0000] {logging_mixin.py:120} INFO - [2023-04-25T20:25:22.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-25T20:25:22.116+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-25T20:25:22.160+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
